
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: icra
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
  backend:
    build: ./backend
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    environment:
      DATABASE_URL: postgresql+psycopg2://postgres:postgres@db:5432/icra
      JWT_SECRET: supersecret_change_me
      JWT_ALGO: HS256
      ADMIN_EMAIL: admin@akropol.com
      ADMIN_PASSWORD: ChangeMe!123
      UPLOAD_DIR: /data/uploads
    volumes:
      - ./backend:/app
      - uploads:/data/uploads
    ports:
      - "8000:8000"
    depends_on:
      - db
  frontend:
    image: node:20
    working_dir: /app
    command: sh -c "npm install && npm run dev -- --host"
    volumes:
      - ./frontend:/app
    ports:
      - "5173:5173"
    environment:
      - NODE_OPTIONS=--max-old-space-size=4096
    depends_on:
      - backend
volumes:
  dbdata:
  uploads:
